---

- name: Docker start
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Docker restart
  ansible.builtin.systemd_service:
    name: docker
    state: restarted

- name: Containerd start
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
